### ISSUE TITLE
Add package homepage

### ISSUE THREAD

**Issue by antagomir** [microbiome/microbiomeDataSets#15]
We can add a simple package homepage with pkgdown, similar to [mia homepage](microbiome.github.io/mia)

**Comment by antagomir** [comment]
Or perhaps the [Bioc page](https://bioconductor.org/packages/release/data/experiment/vignettes/microbiomeDataSets/inst/doc/microbiomeDataSets.html) is sufficient?

**Comment by antagomir** [comment]
See https://pkgdown.r-lib.org/

**Comment by antagomir** [comment]
In fact, best to setup through Github Actions so it is automated.

This already works for mia, just copy the relevant parts from mia repository "mia/.github/workflows"

It may be necessary to set the homepage folder through microbiomeDataSets repository Settings -> Pages -> ....

**Comment by ChouaibB** [comment]
Does the homepage folder setting is done after being merged to master?

**Comment by antagomir** [comment]
Can be done at any point. Just merged so kindly add.
