### ISSUE TITLE
curatedMetagenomicData

### ISSUE THREAD

**Issue by antagomir** [microbiome/microbiomeDataSets#2]
[curatedMetagenomicData](http://www.bioconductor.org/packages/release/data/experiment/vignettes/curatedMetagenomicData/inst/doc/curatedMetagenomicData.html) could be potentially linked to `TSE` (already linked to `phyloseq`).

**Comment by FelixErnst** [comment]
Yes, but Levi has to decide, how and when to do this.

**Comment by FelixErnst** [comment]
Do they actually use the `phyloseq` class? I only found `ExpressionSet` objects in the metadata files.

**Comment by antagomir** [comment]
Abstract says "A conversion function also links taxonomic datasets to the phyloseq package for ecological analyses."

**Comment by antagomir** [comment]
They support TreeSE now.
