### ISSUE TITLE
License

### ISSUE THREAD

**Issue by antagomir** [microbiome/microbiomeDataSets#23]
`BiocCheck()` says:

* Checking License: for restrictive use...
    * NOTE: License 'CC0' unknown; licenses cannot restrict use

Shall we keep CC0, however, for this data package?

**Comment by FelixErnst** [comment]
I would have a look, what other packages are using. On the  Bioc system it doesn't cause an error does it?

It was also accepte during the review. Was this check modified recently?

**Comment by antagomir** [comment]
I do not immediately find the specific commit from the [history](https://github.com/Bioconductor/BiocCheck/commits/db980127219936c6ce44748ed1700d8c9e956e9e/R/checks.R) but anyway this is just a note. And while CC0 is unknown it does not restrict use unnecessarily, it is an open license and as such acceptable I think.

[curatedTCGAData](https://bioconductor.org/packages/release/data/experiment/html/curatedTCGAData.html) and [SingleCellMultimodal](https://bioc.ism.ac.jp/packages/devel/data/experiment/html/SingleCellMultiModal.html) are packages from partially same authors, these are both with Artistic-2.0. But I think the license in these packages are intended to cover package R code, not the ExperimentHub data sets. In fact I have not found notes about data licensing w.r.t. ExperimentHub resources, perhaps understandably as the data sets come from various, sometimes external, sources and it could be misleading to provide general recommendations. 

If we based the decision on the idea that the license is about code, not data, then we could switch to Artistic-2.0, as in mia.

**Comment by FelixErnst** [comment]
https://bioconductor.org/packages/release/data/experiment/html/scRNAseq.html

I guess CC0 is good.

**Comment by antagomir** [comment]
Great observation with the scRNAseq with its CC0 license.

I do agree that CC0 would be a better license for the data, and this was a good finding that scRNAseq also has CC0

**Comment by antagomir** [comment]
Seems to work now.
