### ISSUE TITLE
Removal of the LahtiWAdata and HintikkaXOData datasets

### ISSUE THREAD

**Issue by hpages** [microbiome/microbiomeDataSets#38]
Hi,

About issues #34 and #35.

It seems that the LahtiWAdata and HintikkaXOData datasets were also removed from the `RELEASE_3_19` branch of the **microbiomeDataSets** package in addition to the `devel` branch. Note that this breaks packages that depend on these datasets e.g. https://bioconductor.org/checkResults/3.19/bioc-LATEST/miaViz/

Keep in mind that Bioconductor strongly advices against making breaking changes in release, unless there's a very good reason to do so e.g. a license violation or other legal issue.

Also removing things in devel is ok but there should be a deprecation phase that spans at least a full Bioconductor release (6 months) before the removal actually happens.

Please consider restoring these datasets in release as soon as possible. Let me know or ask on the bioc-devel mailing list if you have questions.

Thanks for your contribution to Bioconductor,

Regards,
H.

**Comment by hpages** [comment]
@antagomir @ake123 @FelixErnst A reminder that this requires your attention. Thanks!

**Comment by ake123** [comment]
I am working on this matter and will be ready soon

**Comment by antagomir** [comment]
Done in #39
