### ISSUE TITLE
Potential Datasets for specific questions

### ISSUE THREAD

**Issue by microsud** [microbiome/microbiomeDataSets#8]
Longitudinal 16S dataset: 
Justin D. Silverman et al 2018. [Dynamic linear models guide design and analysis of microbiota studies within artificial human gut](https://microbiomejournal.biomedcentral.com/track/pdf/10.1186/s40168-018-0584-3.pdf). [code](https://github.com/LAD-LAB/MALLARD-Paper-Code/tree/master/dada2)

Longitudinal multiomics:  
[Deep longitudinal multiomics profiling reveals two biological seasonal patterns in California](https://www.nature.com/articles/s41467-020-18758-1#Sec13),  [data](https://figshare.com/articles/dataset/Multi_Omics_Seasonal_RData/12376508), [code](https://github.com/aametwally/ipop_seasonal)  

Will keep adding interesting ones for reference here.  

13-Jan-2021 
Contamination low-biomass:
Karstens L, Asquith M, Davin S, Fair D, Gregory WT, Wolfe AJ, Braun J, McWeeney S. 2019. [Controlling for contaminants in low-biomass 16S rRNA gene sequencing experiments](https://doi.org/10.1128/mSystems.00290-19). mSystems 4:e00290-19. [code](https://github.com/lakarstens/ControllingContaminants16S)

Buck, M., Garcia, S.L., Fernandez, L. et al. Comprehensive dataset of shotgun metagenomes from oxygen stratified freshwater lakes and ponds. Sci Data 8, 131 (2021). https://doi.org/10.1038/s41597-021-00910-1 "267 shotgun metagenomes from 41 stratified lakes and ponds mainly located in the boreal and subarctic regions, but also including one tropical reservoir and one temperate lake. For most lakes and ponds, the data includes a vertical sample set spanning from the oxic surface to the anoxic bottom layer. The majority of the samples were collected during the open water period, but also a total of 29 samples were collected from under the ice. In addition to the metagenomic sequences, the dataset includes environmental variables for the samples, such as oxygen, nutrient and organic carbon concentrations. The dataset is ideal for further exploring the microbial taxonomic and functional diversity in freshwater environments and potential climate change impacts on the functioning of these ecosystems."

**Comment by FelixErnst** [comment]
Can you create a branch and add a PR for these datasets?

**Comment by microsud** [comment]
Yes will do it!

**Comment by microsud** [comment]
For the Longitudinal 16S dataset by Justin D. Silverman et al 2018., there is a clean version, which is the one I think the main article mostly works with found here: https://github.com/jsilve24/stray/tree/master/data
```
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 18 taxa and 632 samples ]
sample_data() Sample Data:       [ 632 samples by 17 sample variables ]
tax_table()   Taxonomy Table:    [ 18 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 18 tips and 17 internal nodes ]
refseq()      DNAStringSet:      [ 18 reference sequences ]
```

And there is `raw` data for which I need to make the tree myself. 
```
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 413 taxa and 639 samples ]
sample_data() Sample Data:       [ 639 samples by 11 sample variables ]
tax_table()   Taxonomy Table:    [ 413 taxa by 7 taxonomic ranks ]
refseq()      DNAStringSet:      [ 413 reference sequences ]
```
@FelixErnst Which one is preferable?

**Comment by antagomir** [comment]
In my view it would be preferable to build all from the raw data. But I can see this is also more work.

**Comment by FelixErnst** [comment]
I think raw data would also be preferable.

The steps I would suggest:
1. Assemble a TreeSummarizedExperiment from the raw data (Install version 1.7.2 from GitHub)
2. Save the individiual components as `rds` files in `inst/extdata/hub/<dataset-name>/` (If you have questions, have a look at the other datasets or ask me on slack)
3. prepare the metadata file, by creating a new `metadata-<dataset-name>.R` in `inst/scripts` and run the script to create `inst/extdata/metadata-<dataset-name>.csv`
4. make sure that the metadata files passes the check by running `AnnotationHubData::makeAnnotationHubMetadata("../microbiomeDataSets","metadata-<dataset-name>.csv")`

**Comment by microsud** [comment]
Agreed. Same preference for me.

**Comment by antagomir** [comment]
Also make sure that these not already available via [curatedMetagenomicData](https://waldronlab.io/curatedMetagenomicData/articles/articles/available-studies.html).

If issues is not ideal for listing potential data sets, we could use "Projects" or "Wiki" in this repo for that purpose.

**Comment by antagomir** [comment]
We could start collecting interesting data sets to Projects or Wiki, and keep issues for ongoing matters we are working on.

@microsud are you working on some of these data sets actively, what is the status of this issue?

**Comment by antagomir** [comment]
Let's close this for now. We can come back to it if more data is needed.
